const NavigationPaths = {
  APP_REFER: "/app-refer-and-earn",
  APP_PRIVACYPOLICY: "/app-privacy-policy",
  APP_TERM: "/app-terms",
  HOME: "/",
  ABOUTUS: "/about",
  OPENSHORTAPPURL: "/apps",
  FEATURE: "/features",
  SECURITY: "/security",
  WHYPICKZONE: "/why-pickzon",
  CONTEST: "/contest",
  FAQ: "/faq",
  CHAT: "/chat",
  LOGIN: "/login",
  CONTACT: "/contact-us",
  PRIVACYPOLICY: "/privacy-policy",
  TERM: "/terms",
  IPROPERTYPOLICY: "/intellectual-property-policy",
  SEARCHEXPLORE: "/search-and-explore",
  GOLIVE: "/go-live",
  SOCIALCREATOR: "/social-creator",
  CLIPCONTENT: "/clip-content",
  FEEDCONTENT: "/feed-content",
  MALLCONTENT: "/mall-content",
  SERVICES: "/services",
  BUSINESSPAGE: "/best-social-media-app-for-business",
  EARNMONEYPAGE: "/best-short-video-making-app-for-earning-money-in-India",
  CAREER: "/career",
  TIMELINE: "/timeline",

  BLOGS: "/blogs",
  BLOG: "/blog/:title",

  SHARINGMEDIA: "/:pages/:id",
  DASHBOARD: "/dashboard",
  ADSMANAGER: "/dashboard/:pages",
  USERPROFILEPAGE: "/user-profile/:username",
  PAGEFEED: "/feed",
  PAGESAVEFEED: "/save-feed",
  CLIP: "/clip",
  MALL: "/mall",
  FORM: "/create-form",
  CREATEPAGE: "/create-page",
  CREATEPAGEFORM: "/create-page-form",
  COMINGSOON: "/coming-soon",

  INDONESIAHOME: "/indonesiahome",


};

export default NavigationPaths;
